### ISSUE TITLE
Quick Start error

### ISSUE THREAD

**Issue by Scriabing** [zhanghang1989/RegNet-Search-PyTorch#10]
I followed the quick start step,util `No module named 'arch'`. I solved it with `pip install arch`. 
However,when i run`python test_regnet.py --config-file RegNet-Search-PyTorch/configs/RegNetX-4.0GF.ini
`,it get a similar problem which is  `ModuleNotFoundError: No module named 'arch.regnet'`

To be specific，
`(pytorch-OpCounter) root@w-16:~/wxb/pytorch-OpCounter/benchmark# python test_regnet.py --config-file RegNet-Search-PyTorch/configs/RegNetX-4.0GF.ini
Traceback (most recent call last):
  File "evaluate_regnet_zyx.py", line 41, in <module>
    main()
  File "evaluate_regnet_zyx.py", line 28, in main
    arch = importlib.import_module('arch.' + args.arch)
  File "/root/anaconda2/envs/pytorch-OpCounter/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'arch.regnet'
`

**Comment by zhanghang1989** [comment]
`arch` is a folder inside this repo. Did you copy the entire repo?

**Comment by Scriabing** [comment]
of course. First,I checked the arch folder,and find the error`No module named 'arch'`.
However,pip's arch solved the problem. 

> (pytorch-OpCounter) root@w-16:~/wxb/pytorch-OpCounter/benchmark# ls
> evaluate_eff_zyx.py   evaluate_regnet_zyx.py    RegNet-Search-PyTorch

> 
> (pytorch-OpCounter) root@w-16:~/wxb/pytorch-OpCounter/benchmark# cd RegNet-Search-PyTorch/
> (pytorch-OpCounter) root@w-16:~/wxb/pytorch-OpCounter/benchmark/RegNet-Search-PyTorch# ls
> arch         generate_configs.py  README.md         search.py      verify.py
> configs      LICENSE              requirements.txt  test_flops.py
> gen_configs  out_configs          scripts           train.py

> (pytorch-OpCounter) root@w-16:~/wxb/pytorch-OpCounter/benchmark# python evaluate_regnet_zyx.py --config-file RegNet-Search-PyTorch/configs/RegNetX-4.0GF.ini

The regnet_zyx.py is same as your test_flops.py . Anything wrong?
